services:
  - type: web
    name: mesa-ayuda-itil
    env: docker
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: APP_DB_PATH
        value: /var/data/inventarios_helpdesk.db
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
